### ISSUE TITLE
npm install fails on node version 7 on Mac

### ISSUE THREAD

**Issue by acarl005** [jandre/node-userid#15]
`npm install userid` throws an error on node v7.0.0, npm  v3.10.8, on MacOS.

```
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> userid@0.2.0 install /Users/andy/Desktop/node_modules/userid
> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR
  CXX(target) Release/obj.target/userid/src/userid.o
../src/userid.cc:91:7: error: use of undeclared identifier 'getgrouplist'
  if (getgrouplist(*utfname, pw->pw_gid, groups, &ngroups) == -1) {
      ^
../src/userid.cc:99:9: error: use of undeclared identifier 'getgrouplist'
    if (getgrouplist(*utfname, pw->pw_gid, groups, &ngroups) == -1) {
        ^
2 errors generated.
make: *** [Release/obj.target/userid/src/userid.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/andy/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 15.6.0
gyp ERR! command "/Users/andy/.nvm/versions/node/v7.0.0/bin/node" "/Users/andy/.nvm/versions/node/v7.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/andy/Desktop/node_modules/userid
gyp ERR! node -v v7.0.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/andy/Desktop/package.json'
npm WARN Desktop No description
npm WARN Desktop No repository field.
npm WARN Desktop No README data
npm WARN Desktop No license field.
npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/andy/.nvm/versions/node/v7.0.0/bin/node" "/Users/andy/.nvm/versions/node/v7.0.0/bin/npm" "i" "userid"
npm ERR! node v7.0.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE

npm ERR! userid@0.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the userid@0.2.0 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the userid package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs userid
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls userid
npm ERR! There is likely additional logging output above.
```

**Comment by inversion** [comment]
If you include unistd.h it works - https://github.com/jandre/node-userid/pull/16 (http://www.unix.com/man-page/osx/3/getgrouplist/)

I'm not sure where getgrouplist was being defined before, I've not done much in the realm of native Node addons.

**Comment by jhfoo** [comment]
Is there a plan to fix this? I see the same errors as acarl005 at time of writing. Using FBSD 11 w/ node 7.3.0 and npm 4.0.5.

**Comment by inversion** [comment]
I've got an open PR at https://github.com/jandre/node-userid/pull/16 but I'm not sure if that will help you with FreeBSD. Try my branch?

**Comment by meenalaggarwal** [comment]
Userid v0.3.1
I am still facing this issue for node version 7.10.1 & 8.9.4

../src/userid.cc:91:7: error: use of undeclared identifier 'getgrouplist'
if (getgrouplist(*utfname, pw->pw_gid, groups, &ngroups) == -1) {
^
../src/userid.cc:99:9: error: use of undeclared identifier 'getgrouplist'
if (getgrouplist(*utfname, pw->pw_gid, groups, &ngroups) == -1) {
^
2 errors generated.
make: *** [Release/obj.target/userid/src/userid.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack at ChildProcess.onExit (/Users/MeenalAggarwal/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:194:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/MeenalAggarwal/.nvm/versions/node/v7.10.1/bin/node" "/Users/MeenalAggarwal/.nvm/versions/node/v7.10.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! node -v v7.10.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok

Same error for node version 8.9.4
