### ISSUE TITLE
Including userid module results in error

### ISSUE THREAD

**Issue by markhorsman** [jandre/node-userid#17]
Hello,

I'm trying to use your userid module (latest 0.2.0) with node version v4.1.2, npm version 2.14.4 and nvm  version 0.32.0. I get the following errors:

`module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: /home/markhorsman/projects/services/node_modules/userid/build/Release/userid.node: undefined symbol: node_module_register
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/markhorsman/projects/services/node_modules/userid/lib/userid.js:2:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
`

I tried with different node version, rebuilding, removing node_modules and reinstalling/rebuilding but nothing works.

Help would be greatly appreciated. 

Mark Horsman

**Comment by cinderblock** [comment]
Not sure what caused this but it should be fixed in the new 1.0.0-beta version :D Please help me test!

**Comment by cinderblock** [comment]
Dupe of #14
