### ISSUE TITLE
Module Version mismatch (Ubuntu 14.04)

### ISSUE THREAD

**Issue by chev53** [jandre/node-userid#8]
module.js:460
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module version mismatch. Expected 46, got 47.
    at Error (native)
    at Object.Module._extensions..node (module.js:460:18)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/root/backend/node_modules/userid/lib/userid.js:2:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)

**Comment by lukeburns** [comment]
Also experiencing this issue on Ubuntu 14.04.

**Comment by supercrabtree** [comment]
Also having this issue on OS X 10.11.4

**Comment by Cxarli** [comment]
Removing your node_modules folder and reinstalling your project fixes it
